print("\n")
print(" ____________________________________________________________________________ ")
print("|                                                                            |")
print("|                                                                            |")
print("|        _________                                           .___            |")
print("|        \_   ___ \  ____   _____   _____ _____    ____    __| _/____        |")
print("|        /    \  \/ /  _ \ /     \ /     \\__  \  /    \  / __ |/  _ \       |")
print("|        \     \___(  <_> )  Y Y  \  Y Y  \/ __ \|   |  \/ /_/ (  <_> )      |")
print("|         \______  /\____/|__|_|  /__|_|  (____  /___|  /\____ |\____/       |")
print("|                \/             \/      \/     \/     \/      \/             |")
print("|                       C O M P L E T E  M A N D I A N T                     |")
print("|                            O F F E N S I V E   V M                         |")
print("|                                                                            |")
print("|                                Version v2021.2                             |")
print("|                              example@example.com                           |")
print("|____________________________________________________________________________|")
print("|                                                                            |")
print("|                                   Created by                               |")
print("|                            A B C D E F G H I J K L M                       |")
print("|                               Proactive Services                           |")
print("|                         Example Name123 @abcdefghijklmno                   |")
print("|                                   Example 12                               |")
print("|                    unknown Labs Advanced Reverse Engineering               |")
print("|____________________________________________________________________________|")
print("\n")
